#!/bin/sh

which gawk > /dev/null &&
{
gawk -- '
	BEGIN {
		if (ARGV[1] == "-f") {
			show_fname = 1
			ARGV[1] = ""
		}
	}

	ENDFILE {
		if (show_fname)
			print FILENAME, FNR
		else
			print FNR
	}
' "$@"
exit
}

awk -- '
	BEGIN {
		if (ARGV[1] == "-f") {
			show_fname = 1
			ARGV[1] = ""
		}
	}

	{
		fnr[FILENAME] = FNR
	}

	END {
		implicit_stdin = 1
		for (i = 1; i < ARGC; i++)
			if (ARGV[i] != "") {
				implicit_stdin = 0
				if (show_fname)
					print ARGV[i], fnr[ARGV[i]]
				else
					print fnr[ARGV[i]]
			}

		if (implicit_stdin)
			if (show_fname)
				print "-", fnr["-"]
			else
				print fnr["-"]
	}
' "$@"
